services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gradified
      POSTGRES_PASSWORD: npg_OCd09wzJVktu
      POSTGRES_DB: maths_engine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: