services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: maths-backend
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maths-frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend